Solution for api-serializers
mate-academy/py-api-serializers pull request #420
Opened 2024-01-05 20:03 UTC by nsdNite

2024-01-06 12:58 UTC, vasylhnatiuk requested changes

2024-01-06 12:58 UTC, vasylhnatiuk commented on cinema/views.py
> +    queryset = Movie.objects.all()
You should optimize your queryset

2024-01-06 12:58 UTC, vasylhnatiuk commented on cinema/views.py
> +    queryset = MovieSession.objects.all()
You should optimize your queryset

2024-01-06 12:58 UTC, vasylhnatiuk commented on cinema/views.py
> +    queryset = Order.objects.all()
You should optimize your queryset

2024-01-06 12:58 UTC, vasylhnatiuk commented on cinema/views.py
> +    queryset = Ticket.objects.all()
You should optimize your queryset

2024-01-07 12:43 UTC, ArsenPidhoretskyi requested changes

2024-01-07 12:43 UTC, ArsenPidhoretskyi commented on cinema/urls.py
> +urlpatterns = [path("", include(router.urls))]
No need to include router when base is not provided.
Use urlpatterns = router.urls

2024-01-07 15:05 UTC, vasylhnatiuk approved these changes

2025-04-08 11:57 UTC, closed without merging