done
mate-academy/py-api-serializers pull request #503
Opened 2024-04-04 17:35 UTC by VladyslavShepilov

2024-04-04 18:16 UTC, ArsenPidhoretskyi requested changes
Please fix tests

2024-04-04 18:16 UTC, ArsenPidhoretskyi commented on cinema/urls.py
> +] + router.urls
```suggestion
urlpatterns = router.urls
```
Simplify this

2024-04-04 19:06 UTC, VladyslavShepilov commented
I do not understand why test_post_invalid_movies when I mark actors as read_only field in my MovieSerializer and MovieListSerializer

2024-04-04 19:24 UTC, EdAlekseiev approved these changes

2024-04-04 19:25 UTC, EdAlekseiev requested changes
Fixed tests, please. If you stuck with it, you can write to chat of your group

2024-04-05 08:21 UTC, ArsenPidhoretskyi approved these changes
Well done!

2025-10-24 20:36 UTC, closed without merging