Solution
mate-academy/py-api-serializers pull request #518
Opened 2024-05-03 18:17 UTC by AlexTsikhun

2024-05-03 21:38 UTC, ArsenPidhoretskyi requested changes

2024-05-03 21:38 UTC, ArsenPidhoretskyi commented on cinema/urls.py
> +]
Use urlpatterns = router.urls

2024-05-03 21:54 UTC, AlexTsikhun commented on cinema/urls.py
> +]
I'm wondering if I set the type annotations correctly?

2024-05-22 17:12 UTC, vasylhnatiuk requested changes

2024-05-22 17:12 UTC, vasylhnatiuk commented on cinema/views.py
> +    def get_serializer_class(self) -> Type[
```suggestion
    def get_serializer_class(self) -> Type[ModelSerializer]
```

2024-05-22 17:12 UTC, vasylhnatiuk commented on cinema/views.py
> +    def get_serializer_class(self) -> Type[
it is not nessasary to write all of serializers

2024-05-22 17:12 UTC, vasylhnatiuk commented on cinema/views.py
> +    def get_serializer_class(self) -> Type[
change everywhere

2024-05-22 17:12 UTC, vasylhnatiuk commented on .flake8
>      tests
add newline

2024-05-23 09:46 UTC, Dimosphen1 approved these changes
LGTM, well done! One comment is left for consideration

2024-05-23 09:46 UTC, Dimosphen1 commented on cinema/migrations/0004_alter_genre_name.py
Do not modify migrations that are already present in the project without a need in the future, leave them in an initial state

2026-05-17 10:00 UTC, closed without merging